excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://o1ezhon.github.io
title: Awesome
email: o1ezhon@ya.ru
author: o1ezhon
description: My awesome new site
paginate: 20
google_analytics: 